#!/bin/bash

command=$1
serverName="ES6 Web Server"

if [ "$command" != "" ]; then
  dir=$(pwd)
  case $command in
    "start")
      ./bootstrap/nserver-start.sh
      if [ "$serverName" = "web" ]; then
        service httpd restart
      fi
      ;;
    "restart")
      ./bootstrap/nserver-stop.sh
      ./bootstrap/nserver-start.sh
      if [ "$serverName" = "web" ]; then
        service httpd restart
      fi
      ;;
    "startDebug")
      echo "Debug version of server can only be viewed direct port access."
      ./bootstrap/nserver-debugStart.sh
      ;;
    "status")
      ./bootstrap/nserver-status.sh
      ;;
    "stop")
      ./bootstrap/nserver-stop.sh
      ;;
    "clearLog")
      truncate -s 0 server.log
      ;;
    "assureRunning")
      ./bootstrap/nserver-assure.sh
      ;;
    *)
      echo "Invalid server command."
      ;;
  esac
else
  echo "Enter a server command start|startDebug|stop|status|clearLog|assureRunning"
fi
